### ISSUE TITLE
Crashing containers calling libpthread

### ISSUE THREAD

**Issue by pceric** [BonnierNews/logstash_exporter#8]
I just pulled a fresh round of images from DockerHub today and they all crash out immediately with the following error:

> /logstash_exporter: relocation error: /lib/libpthread.so.0: symbol h_errno, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

**Comment by christoe** [comment]
Hi @pceric! Sorry about the inconvenience! The reason behind this is that we used prometheus glibc-image as a base, which includes libpthread because busybox didn't ship with it in the past. Now they have added it, and this results in two versions of libpthread in the resulting image. Fix is coming up in a few minutes. Thanks for reporting!

**Comment by pceric** [comment]
Thanks for the quick fix and for the docker tag. Great project!
